services:
  bsi-docs:
    container_name: bsi-docs
    image: mcr.microsoft.com/devcontainers/typescript-node:1-20-bullseye
    user: node
    volumes:
      - .:/app
    ports:
      - 4334:4321
    working_dir: /app
    # command: bash scripts/build.sh
    command: npm run dev
    networks:
      - bsi-docs-network

networks:
  bsi-docs-network:
    driver: bridge